### ISSUE TITLE
highlighting doesnt work

### ISSUE THREAD

**Issue by aMOPel** [LoricAndre/oneterm#3]
with fzf.vim plugin and ":Ag", also using bat in PATH for preview
![Screenshot from 2021-04-15 22-33-13](https://user-images.githubusercontent.com/36712072/114934842-be201f00-9e3a-11eb-8308-40efc967e5f4.png)
With :OneTerm ag
![Screenshot from 2021-04-15 22-33-26](https://user-images.githubusercontent.com/36712072/114934844-bf514c00-9e3a-11eb-8040-806f9e3df384.png)

**Comment by LoricAndre** [comment]
This is probably due to how I highlight the search result in the preview buffer, I'll take a look

**Comment by aMOPel** [comment]
oh i actually get preview highlighting with :OneTerm lines

**Comment by LoricAndre** [comment]
Yes, it's specific to rg and ag I think, I don't have the code with me rn so I can't say for sure

**Comment by aMOPel** [comment]
but also the highlighting in the fzf windows is kinda missing, not just the preview windows, without the matches are harder to read.
also for `:OneTerm commits` for example

**Comment by LoricAndre** [comment]
This is foxed in the last few commits.
