### ISSUE TITLE
using term with Sessions clutters buffers

### ISSUE THREAD

**Issue by aMOPel** [LoricAndre/oneterm#7]
i use a Session.vim file (with [obsession](https://github.com/tpope/vim-obsession)) to continue where i left and when i use a term and quit and then go back into the session the old term buffer is still alive, but not used by the `:OneTerm term` command which opens a new term, so gradually i accumulate a billion terms.

**Comment by LoricAndre** [comment]
This will be fixed next time I merge dev with master !

**Comment by LoricAndre** [comment]
Done in 1ef08e68847d0768c3e144b7528ce1d75ec2292d !

**Comment by aMOPel** [comment]
I guess a simple workaround would be to add smth along the lines of to your vimrc.

`au vimleave * "kill all term buffers here"`

But anyway it would be cool if the old term was picked up by oneterm term, when coming back to a session in case it still lives

**Comment by LoricAndre** [comment]
That's basically what I want to do, I just put the autocommand at the wrong spot in the code, it's a 10 sec fix I'll do it now

**Comment by LoricAndre** [comment]
Done in 493aec12e9ad21cac7c53d2e93e2f28e66aaa089 and 20da07b5bcf23ab63295f45e818e60d0f5402011
