### ISSUE TITLE
quitting ranger opens the file anyways

### ISSUE THREAD

**Issue by aMOPel** [LoricAndre/oneterm#8]
in my mind desired behavior would be, choose a file and open it with ranger (with `l or enter`) and it opens in the current buffer,
but when you quit (with `q`) nothing happens.

currently the file is opened in the current buffer anyways.

also it would be nice to have some option to open the selected file in a new tab or split (ideally same mappings as fzf), but i guess ranger captures all the output, so its maybe not so easy, but i dont know.

**Comment by LoricAndre** [comment]
I don't think there's anything I can do, `q` apparently selects the file in ranger... I usually exit with `:q` so I hadn't noticed
